CREATE TABLE CHAIN_STORE (
  idCHAIN_STORE SERIAL  NOT NULL ,
  name VARCHAR(45)   NOT NULL ,
  web VARCHAR(45)      ,
PRIMARY KEY(idCHAIN_STORE));




CREATE TABLE PRODUCT (
  idPRODUCT SERIAL  NOT NULL ,
  name VARCHAR(20)   NOT NULL ,
  description VARCHAR(255)    ,
  category VARCHAR(20)   NOT NULL ,
  sub_category VARCHAR(20)      ,
PRIMARY KEY(idPRODUCT));




CREATE TABLE CART (
  idCART SERIAL  NOT NULL ,
  CHAIN_STORE_idCHAIN_STORE INTEGER   NOT NULL ,
  modified TIMESTAMP    ,
  name VARCHAR(20)   NOT NULL   ,
PRIMARY KEY(idCART)  ,
  FOREIGN KEY(CHAIN_STORE_idCHAIN_STORE)
    REFERENCES CHAIN_STORE(idCHAIN_STORE)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX CART_FKIndex1 ON CART (CHAIN_STORE_idCHAIN_STORE);


CREATE INDEX IFK_Rel_07 ON CART (CHAIN_STORE_idCHAIN_STORE);


CREATE TABLE STORE (
  idSTORE SERIAL  NOT NULL ,
  CHAIN_STORE_idCHAIN_STORE INTEGER   NOT NULL ,
  map_lat DECIMAL(4,7)    ,
  map_long DECIMAL(4,7)    ,
  city VARCHAR(20)    ,
  street VARCHAR(20)    ,
  house_number INTEGER    ,
  country VARCHAR(45)    ,
  post_code VARCHAR(20)    ,
  phone INTEGER    ,
  email VARCHAR(45)      ,
PRIMARY KEY(idSTORE)  ,
  FOREIGN KEY(CHAIN_STORE_idCHAIN_STORE)
    REFERENCES CHAIN_STORE(idCHAIN_STORE)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX STORE_FKIndex1 ON STORE (CHAIN_STORE_idCHAIN_STORE);


CREATE INDEX IFK_Rel_03 ON STORE (CHAIN_STORE_idCHAIN_STORE);


CREATE TABLE CART_has_PRODUCT (
  idCART_has_PRODUCT SERIAL  NOT NULL ,
  CART_idCART INTEGER   NOT NULL ,
  PRODUCT_idPRODUCT INTEGER   NOT NULL   ,
PRIMARY KEY(idCART_has_PRODUCT, CART_idCART, PRODUCT_idPRODUCT)    ,
  FOREIGN KEY(CART_idCART)
    REFERENCES CART(idCART)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(PRODUCT_idPRODUCT)
    REFERENCES PRODUCT(idPRODUCT)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX CART_has_PRODUCT_FKIndex1 ON CART_has_PRODUCT (CART_idCART);
CREATE INDEX CART_has_PRODUCT_FKIndex2 ON CART_has_PRODUCT (PRODUCT_idPRODUCT);


CREATE INDEX IFK_Rel_05 ON CART_has_PRODUCT (CART_idCART);
CREATE INDEX IFK_Rel_06 ON CART_has_PRODUCT (PRODUCT_idPRODUCT);


CREATE TABLE CHAIN_STORE_has_PRODUCT (
  idCHAIN_STORE_has_PRODUCT SERIAL  NOT NULL ,
  CHAIN_STORE_idCHAIN_STORE INTEGER   NOT NULL ,
  PRODUCT_idPRODUCT INTEGER   NOT NULL ,
  price DECIMAL(7,2)      ,
PRIMARY KEY(idCHAIN_STORE_has_PRODUCT, CHAIN_STORE_idCHAIN_STORE, PRODUCT_idPRODUCT)    ,
  FOREIGN KEY(CHAIN_STORE_idCHAIN_STORE)
    REFERENCES CHAIN_STORE(idCHAIN_STORE)
      ON DELETE CASCADE
      ON UPDATE CASCADE,
  FOREIGN KEY(PRODUCT_idPRODUCT)
    REFERENCES PRODUCT(idPRODUCT)
      ON DELETE CASCADE
      ON UPDATE CASCADE);


CREATE INDEX CHAIN_STORE_has_PRODUCT_FKIndex1 ON CHAIN_STORE_has_PRODUCT (CHAIN_STORE_idCHAIN_STORE);
CREATE INDEX CHAIN_STORE_has_PRODUCT_FKIndex2 ON CHAIN_STORE_has_PRODUCT (PRODUCT_idPRODUCT);


CREATE INDEX IFK_Rel_01 ON CHAIN_STORE_has_PRODUCT (CHAIN_STORE_idCHAIN_STORE);
CREATE INDEX IFK_Rel_02 ON CHAIN_STORE_has_PRODUCT (PRODUCT_idPRODUCT);



